name: learn-github-actions-testing
on: [push]
jobs:
  check-bats-version:
    runs-on: macos-13-xl-m1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
